services:
  producer-api:
    build: ./producer-api
    container_name: fraud_producer_api
    ports:
      - "8000:8000"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_PRIVATE_IP}:9092
    restart: unless-stopped
